"""sync supabase schema

Revision ID: b596fe3ea2c1
Revises: 9a0d4953ff02
Create Date: 2026-04-18 13:46:49.475702

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b596fe3ea2c1"
down_revision: Union[str, Sequence[str], None] = "9a0d4953ff02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag", sa.Column("is_system", sa.Boolean(), nullable=False))
    op.add_column("tag", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(None, "tag", "user", ["user_id"], ["id"])
    op.add_column("userstats", sa.Column("date_of_birth", sa.Date(), nullable=True))
    op.add_column(
        "userstats",
        sa.Column(
            "gender",
            sa.Enum(
                "male", "female", "non_binary", "prefer_not_to_say", name="genderenum"
            ),
            nullable=False,
        ),
    )
    op.add_column("video", sa.Column("draft", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "draft")
    op.drop_column("userstats", "gender")
    op.drop_column("userstats", "date_of_birth")
    op.drop_constraint(None, "tag", type_="foreignkey")  # type: ignore
    op.drop_column("tag", "user_id")
    op.drop_column("tag", "is_system")
    # ### end Alembic commands ###
