"""add asset_identifier to video

Revision ID: c458b680b413
Revises: b596fe3ea2c1
Create Date: 2026-04-18 14:38:04.723129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c458b680b413"
down_revision: Union[str, Sequence[str], None] = "b596fe3ea2c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("video", sa.Column("asset_identifier", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video", "asset_identifier")
    # ### end Alembic commands ###
